language: node_js
node_js: --lts
before_script:
  - git config user.name "straydragon"
  - git config user.email "straydragonv@gmail.com"
  - sed -i'' "s~https://github.com/StrayDragon/straydragon.github.io.git~https://${ACCESS_TOKEN}@github.com/StrayDragon/straydragon.github.io.git~" _config.yml
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
